# Generated by Django 3.2.20 on 2024-04-11 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('6617687f-887b-4e2b-8904-88ffcbd2635a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_image', models.ImageField(upload_to='static/imges/brands')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand_models',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('6617687f-887b-4e2b-8904-88ffcbd2635a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=100)),
                ('model_image', models.ImageField(upload_to='static/imges/models')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedyapp1.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('6617687f-887b-4e2b-8904-88ffcbd2635a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('6617687f-887b-4e2b-8904-88ffcbd2635a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('spare_name', models.CharField(max_length=100)),
                ('spare_image', models.ImageField(upload_to='static/imges/spares')),
                ('spare_price', models.CharField(max_length=100)),
                ('in_stock', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=4)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedyapp1.brand_models')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('6617687f-887b-4e2b-8904-88ffcbd2635a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='speedyapp1.cart')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedyapp1.spares')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
