# Generated by Django 3.2.20 on 2024-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedyapp1', '0003_rename_price_cartitem_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
