# Generated by Django 3.2.20 on 2024-04-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedyapp1', '0004_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
