# Generated by Django 3.2.20 on 2024-04-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedyapp1', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spares',
            name='spare_price',
            field=models.IntegerField(),
        ),
    ]
