# Generated by Django 3.2.20 on 2024-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedyapp1', '0007_alter_spares_spare_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
