# Generated by Django 3.2.20 on 2024-04-11 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240411_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0c3592c5-ce4a-4f00-befc-f9d72b7fdb35'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
